version: '3.9'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bookStore
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./bookStore.sql:/docker-entrypoint-initdb.d/init.sql

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8080:8080"
    volumes:
      - keycloak-data:/opt/keycloak/data

  back-end:
    build: ./back-end
    ports:
      - "4002:4002"
    depends_on:
      - mysql
      - keycloak

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - back-end

volumes:
  mysql-data:
  keycloak-data:
